# Generated by Django 4.1.6 on 2023-02-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_roll_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
